### ISSUE TITLE
Warn about performance regressions

### ISSUE THREAD

**Issue by hanno-becker** [pq-code-package/mlkem-native#202]
It would be nice if the benchmarking CI could compare new vs. `main` performance numbers and warn, through a comment on the PR, if there's a target experiencing a major (>5%, say?) regression.

**Comment by hanno-becker** [comment]
@potsrevennil Do you know how to do this?

**Comment by potsrevennil** [comment]
I'm thinking about using `git note` although I've never used it before

For example, we could add summary of the benchmarking result (whenever there's a new commit on main) via `git note`, which add notes to commit without touching commit itself, thus would not pollute the history. 
Then we could just simply diff the notes between different commits on the main branch

But this might required some times to trial and error, as I said I've never tried this before 😄

**Comment by potsrevennil** [comment]
Oh, there's an easier way
the benchmarkaction/github-action-benchmark provided `alert-threshold` and `comment-on-alert`, this should be able to achieve what we want

**Comment by hanno-becker** [comment]
@potsrevennil That sounds promising indeed!

**Comment by mkannwischer** [comment]
Done by #424
