### ISSUE TITLE
Appropriate comments in header and body files

### ISSUE THREAD

**Issue by rod-chapman** [pq-code-package/mlkem-native#211]
For future consideration:

In the PQCrystals/Kyber reference code, there is a trend for all functions comments to appear in the body (*.c) files
for all translation units. This is counter to common practice, where what the user/client needs to know should be in the
header (.h) file, while additional information pertaining to the implementation should only appear in the body.

This Issue raised to track resolution for all units.

**Comment by hanno-becker** [comment]
@rod-chapman Can you do this?

**Comment by rod-chapman** [comment]
We should first agree a standard for this. Then do one of the lowest-level modules to see how it looks (e.g reduce.c) before moving on to others.

**Comment by hanno-becker** [comment]
@rod-chapman I think you are right that it is uncommon to have function documentation in the .c file. The format of the documentation is a separate question. So I'd say let's move the documentation over to .h in a first step, and then discuss & rework what we want it to say exactly -- I assume there will be a lot of changes upcoming with CBMC.

**Comment by mkannwischer** [comment]
Related to #434. 

We should also automatically generate documentation from these comments - I'll open a separate issue for that.

**Comment by mkannwischer** [comment]
I guess we can close this one and add to #434 that we need to make sure all functions have documentation in the headers.
