### ISSUE TITLE
Show performance difference to `main` in benchmark output of CI

### ISSUE THREAD

**Issue by hanno-becker** [pq-code-package/mlkem-native#223]
In addition to (and perhaps as a first step towards) #202, the benchmarking CI should always print in the CI log the performance delta of the current commit under test and `main`. At the moment, there is no really quick way to find out how performance compares: You either have to eyeball the GH page graphs (the tooltips don't really work for large commit messages), or manually find the last CI run on `main` -- both of which is inconvenient.

- [ ] The benchmarking CI log shows the relative speedup/slowdown of the current commit w.r.t. `main`

**Comment by hanno-becker** [comment]
@potsrevennil Can you do this as well?

**Comment by potsrevennil** [comment]
ok
