### ISSUE TITLE
Automatically terminate CI EC2 instances after some time

### ISSUE THREAD

**Issue by hanno-becker** [pq-code-package/mlkem-native#274]
We are using https://github.com/machulav/ec2-github-runner to spin up an tear down EC2 instances for the CI. However, there's often the odd instance out which does _not_ get torn down for some reason. In that case, we have to manually spot and fix this to avoid unnecessary cost.

This issue tracks finding a more robust solution to this that takes the human out of the loop, _most of the time_. This is likely a combination of changing how we use https://github.com/machulav/ec2-github-runner, and EC2 configuration changes.

**Comment by mkannwischer** [comment]
I think this got fixed by https://github.com/pq-code-package/mlkem-native/pull/414. @hanno-becker, do you agree? Or are you still sometimes seeing instances not being properly terminated?

**Comment by hanno-becker** [comment]
I haven't seen that since, no. Closing.
