### ISSUE TITLE
Clarifying What We Provide in a Release

### ISSUE THREAD

**Issue by potsrevennil** [pq-code-package/mlkem-native#290]
We've set up some criteria for alpha-release, but we've not yet clarify what we actually want to provide as a release.

1. Do we want to provide an easy-to-use build system which allow users to easily integrate into their projects ?

2. Do we want to be able to build a static/dynamic-linked library for MLKEM API ?

3. Do we want to release pre-built static/dynamic-linked library via GitHub release, so that users won't need to bother manually build themselves ?

4. Any other thoughts ?

@hanno-becker @mkannwischer what's your thoughts on this ?

**Comment by planetf1** [comment]
I'd agree @mkannwischer - in terms of the code artifacts, but also the docs are clear on the status, sets the right expectation for anyone consuming the library, documents any known limitations/caveats. Much of that is already in the readme. Also we document our security reporting approach (to some extent it is in that we have a file, it says to open a regular issue - is that ok?)

**Comment by hanno-becker** [comment]
Thanks for raising this @potsrevennil.

I am not yet sold on the idea that mlkem-native is _only_ to be used by taking code, rather than a build artifact. It would seem that for some customers, merely consuming a resulting `libmlkem_native.a`would be most convenient -- esp. seeing how small the public API is.

**Comment by mkannwischer** [comment]
Conclusion so far is: The alpha-release is going to be code only. 
For subsequent releases, it will depend on what consumers want/need. 

Once formal verification of asm is in place, we will likely want to ship a library. 

Closing this for now - re-open if you disagree.
