### ISSUE TITLE
CBMC: Understand and use the correct shape of stub-harnesses for spec-proofs

### ISSUE THREAD

**Issue by hanno-becker** [pq-code-package/mlkem-native#325]
When we verify specs, we still need to provide stub harnesses invoking the function-under-proof. Morally, it seems that those harnesses should be irrelevant, but https://github.com/pq-code-package/mlkem-c-aarch64/pull/306 (specifically this commit https://github.com/pq-code-package/mlkem-c-aarch64/commit/a95a2ce56cf11567242a8ff80d6219986cc2851c) suggest that this may be wrong: In this commit, the spec for `poly_add()` does not provide any bound on the `r` buffer, and yet the proof goes through. This is likely because the harness allocates the data on the stack, which may inadvertently add to the pre-conditions of `poly_add` -- it's likely that an uninitialized `poly*` should have been passed.

- [x] Understand what the correct shape of harnesses for spec-proofs is
- [x] Apply needed changes throughout
- [x] Adjust the CBMC proof guide accordingly

**Comment by hanno-becker** [comment]
@rod-chapman Please comment

**Comment by rod-chapman** [comment]
I agree that the harness should infer a little information as possible, so passing an unitialized pointer rather than a pointer to a stack-allocated local object feels OK to me, assuming the proofs all succeed. We need to confirm this advice with CBMC team, then update the Proof Guide accordingly.

**Comment by hanno-becker** [comment]
The CBMC team has confirmed this.

**Comment by hanno-becker** [comment]
@rod-chapman Let me know when you have updated the proof guide, and then we can close this.
