### ISSUE TITLE
CBMC: State + prove spec for `pack_ciphertext`

### ISSUE THREAD

**Issue by mkannwischer** [pq-code-package/mlkem-native#389]

**Comment by hanno-becker** [comment]
You can probably just inline that.

**Comment by mkannwischer** [comment]
`unpack_ciphertext` is not inlined. Why not inline that? I think it should be consistent?

**Comment by hanno-becker** [comment]
If the caller proof goes through fine with inlining -- which it does -- I think it's unnecessary effort to have a separate CBMC proof
