### ISSUE TITLE
Upload non-opt benchmarks

### ISSUE THREAD

**Issue by mkannwischer** [pq-code-package/mlkem-native#406]
Additionally upload non-opt benchmarks to https://pq-code-package.github.io/mlkem-native/dev/bench/.

**Comment by hanno-becker** [comment]
Ideally this should be done so we also see benchmark progression retroactively.

**Comment by mkannwischer** [comment]
retroactive benchmarking is a separate issue that we can address afterwards. Likely together when adding RISC-V support.
