### ISSUE TITLE
Consider dropping loop ASSIGNS contract now CBMC can infer it

### ISSUE THREAD

**Issue by rod-chapman** [pq-code-package/mlkem-native#450]
CBMC 6.4.0 has gained the ability to automatically infer the ASSIGNS contract for simple loops.

We should evaluate this feature and decide if we can and should drop the ASSIGNS contract
in loop statement where it is possible to do so. This reduces burden on developers and maintainers,
and decreases clutter in the code.

Initial result: All but 1 of the ASSIGNS contracts in poly.c can be removed with no loss in
proof performance. The 1 still required is in poly_basemul_montgomery_cached(), which
has a more complex loop body that assigns to _slices_ of the target array, so not surprising
that CBMC is not able to infer the correct contract in this case.

**Comment by hanno-becker** [comment]
@rod-chapman This sounds great. The fewer annotations, the better (assuming the proof performance is OK). Can you open a PR demonstrating the new feature please?

**Comment by rod-chapman** [comment]
I will open a PR and branch now. I have it done on poly.c
