### ISSUE TITLE
Demonstrate build with all 3 parameter sets in CI

### ISSUE THREAD

**Issue by rod-chapman** [pq-code-package/mlkem-native#457]
Consumers of mlkem-native (e.g. other major cryptographic libraries) will likely want to include all three ML-KEM parameter sets for their users.

We therefore need to demonstrate that mlkem-native can be built 3 times with MLKEM_K=[2,3,4] and the resulting object files combined into a single library with no clashes.

On platforms that support it, this should be demonstrated for producing both a static- and a dynamically-linked library.

**Comment by hanno-becker** [comment]
I agree.

@mkannwischer @potsrevennil What are your thoughts on changing the build so it generates a `libmlkem{512,768,1024}.a` in the interim, and we demonstrate in a separate test that all those link together into `libmlkem.a`?

**Comment by rod-chapman** [comment]
I like that idea. Some consumers might want just one (small) library that implements just 1 parameter set. Some consumers might want all 3. We need to demonstrate that both options are possible and easy.

**Comment by hanno-becker** [comment]
No, they are all namespaced. Doing things without duplication would be out of scope initially.

**Comment by mkannwischer** [comment]
@rod-chapman - is this something you need relatively soon or just an idea that we may want to consider when we have time? 

> I agree.
> 
> @mkannwischer @potsrevennil What are your thoughts on changing the build so it generates a `libmlkem{512,768,1024}.a` in the interim, and we demonstrate in a separate test that all those link together into `libmlkem.a`?

I agree with that proposal - but for now this is just for our build system, not something that we ship in releases or want the consumer to use directly. If we actually want to ship a library that is going to be much more work - esp. w.r.t. Keccak implementation variants.

> No, they are all namespaced. Doing things without duplication would be out of scope initially.

I also strongly agree with this. If you want to do that, you will have to re-work a lot of code and move further away from the reference implementation which is not something we want to do unless we have to. 
If this is something that's important for one of our (potential) consumers, then we should discuss that separately.

**Comment by hanno-becker** [comment]
> I agree with that proposal - but for now this is just for our build system, not something that we ship in releases or want the consumer to use directly. If we actually want to ship a library that is going to be much more work - esp. w.r.t. Keccak implementation variants.

I agree. But even if we just showcase the possibility in our own build system, that's useful.

**Comment by potsrevennil** [comment]
> I agree.
> 
> @mkannwischer @potsrevennil What are your thoughts on changing the build so it generates a `libmlkem{512,768,1024}.a` in the interim, and we demonstrate in a separate test that all those link together into `libmlkem.a`?

I would also agree on this proposal and like the idea of showcasing the possibility in the build system.

As @mkannwischer mentioned in the long term, if we aim to ship a library as part of a release, it will require additional effort. Specifically, we need to clarify our approach to shipping the library in relation to all implementation variants.
