### ISSUE TITLE
Make test scripts usable in older versions of Python

### ISSUE THREAD

**Issue by hanno-becker** [pq-code-package/mlkem-native#560]
The Python scripts in `scripts` require at least Python 3.10, and hence don't work out of the box on systems with older Python versions. 

The test lib should be rewritten to not use any newer Python features -- this should be as plain as possible to ensure maximum usability. 

It's TBD what version of Python we should require.

**Comment by hanno-becker** [comment]
@potsrevennil What are your thoughts here? How much complexity is inherent, and how much can be shaved off?

**Comment by mkannwischer** [comment]
MacOS still comes with 3.9 by default. Debian and Ubuntu ship newer versions.

I think we should definitely support 3.9 and above.

**Comment by hanno-becker** [comment]
> Debian and Ubuntu ship newer versions.

Yes, but Ubuntu 20.04 comes with 3.8 for example.

**Comment by hanno-becker** [comment]
Addressed for 3.8 by #562
