### ISSUE TITLE
AVX2 backend not enabled by default

### ISSUE THREAD

**Issue by dkostic** [pq-code-package/mlkem-native#574]
**Describe the bug**
Since this [commit](https://github.com/pq-code-package/mlkem-native/commit/b94f8ce2e47e26ae93a54f0c6a04e83ebbec6360#diff-c96841396bcc20102aa6e34c2da581c69d98ec0099f196e388f15e0b071b339a) the AVX2 backend doesn't compile by default. My platform is a c7i EC2 instance with Intel(R) Xeon(R) Platinum 8488C, running Ubuntu 22.04 with gcc 11.4.0.

**Platform**: x86_64 Linux

**Compiler**: gcc 11.4.0

**How to reproduce**
```
make clean; make -j
```
One of the easiest ways to confirm that the AVX2 backend is not enabled is to run any of the benchmarks and compare the numbers against the expected ones (https://pq-code-package.github.io/mlkem-native/dev/bench/). Otherwise, you can insert `#error fail_the_build_if_this_is_compiled` for example [here](https://github.com/pq-code-package/mlkem-native/blob/2a6999efbacaa1cfca6eff6fb947422dce954236/mlkem/native/x86_64/src/rej_uniform_avx2.c#L14) and  try to build the library which will succeed, meaning that the AVX2 backend is not compiled.

**Expected behavior**

**Additional context**

**Comment by hanno-becker** [comment]
Thank you @dkostic for reporting this. We should have caught this in CI. Can you confirm whether the build fails with `FORCE_X86_64`?

**Comment by hanno-becker** [comment]
@dkostic can you confirm that #578 fixed the issue for you?

**Comment by dkostic** [comment]
Thanks for quick reaction! The fix in https://github.com/pq-code-package/mlkem-native/pull/578 works on my machine as well.
