### ISSUE TITLE
Test or remove BMI code from AVX2 backend

### ISSUE THREAD

**Issue by hanno-becker** [pq-code-package/mlkem-native#577]
The AVX2 rejection sampling code inherited from the official Kyber implementation some ifdef's regarding the availability of bit manipulation instructions. Those are untested at present. 

Remove all code guarded by BMI, or (a) test it, (b) evaluate the range of targets where this is available, and (c) show that it actually helps performance (if it does).

For now I am inclined to just remove it. We cannot have untested code in the library.

**Platform**: 
Which platform does this concern?
- [ ] platform independent
- [ ] aarch64
- [x] x86_64
- [ ] rv64
- [ ] other

**Comment by hanno-becker** [comment]
@dkostic Can you comment on this by chance?

**Comment by dkostic** [comment]
Thanks for quick reaction! The fix in #578 works on my machine as well.

**Comment by hanno-becker** [comment]
@mkannwischer Do you have time to take care of this?
