### ISSUE TITLE
ML-KEM Benchmarking fails: Shows 0 cycles

### ISSUE THREAD

**Issue by AdityaKoranga** [pq-code-package/mlkem-native#587]
## Issue Description

Hi,
We are trying to benchmark ML-KEM, but it isn't working properly on our env.

`make bench` seems to be working fine
 but execution of `./test/build/mlkem512/bin/bench_mlkem512` doesn't show the expected results.

```shell
charm@charm:~/slum_dawg/mlkem-native$ ./test/build/mlkem512/bin/bench_mlkem512

   keypair cycles = 0
    encaps cycles = 0
    decaps cycles = 0

           percentile      1     10     20     30     40     50     60     70     80     90     99
   keypair percentiles:      0      0      0      0      0      0      0      0      0      0      0
    encaps percentiles:      0      0      0      0      0      0      0      0      0      0      0
    decaps percentiles:      0      0      0      0      0      0      0      0      0      0      0
```

## Setup Details

OS: Ubuntu 22.04.4 LTS 
CPU: Intel 8260 CPU @ 2.40GHz

**Comment by mkannwischer** [comment]
You need to explicitly pass the cycle counting method (NO, PMU, PERF, M1) to the `make bench` call. 
Try `make bench CYCLES=PERF` or  `make bench CYCLES=PMU` . Unfortunately, `CYCLES` default to NO which results in the all zeros you are getting.

I've changed the default behavior in #588  to error in case no explict CYCLES are passed when building the benchmarking libraries.

**Comment by hanno-becker** [comment]
#588 merged

**Comment by AdityaKoranga** [comment]
Hi @mkannwischer 

Thanks for the quick response.

I tried with `make bench CYCLES=PMU` and it is working fine:

```shell
charm@charm:~/slum_dawg/588-mlkem-native/mlkem-native$ ./test/build/mlkem512/bin/bench_mlkem512
   keypair cycles = 24778
    encaps cycles = 33445
    decaps cycles = 44858

           percentile      1     10     20     30     40     50     60     70     80     90     99
   keypair percentiles:  22743  24253  24503  24612  24694  24778  24880  25012  25329  26256  42460
    encaps percentiles:  31463  32716  33080  33223  33317  33445  33635  33864  34366  35862  56895
    decaps percentiles:  41990  43908  44428  44552  44707  44858  45041  45358  45977  47910  77798
```

But when I tried with `make bench CYCLES=PERF` it gave me output `read: Bad file descriptor`:

```shell
charm@charm:~/slum_dawg/588-mlkem-native/mlkem-native$ ./test/build/mlkem512/bin/bench_mlkem512
read: Bad file descriptor
```

**Comment by hanno-becker** [comment]
@AdityaKoranga you need to run as root I think.

Consider also using the test script which makes this process easier: `tests bench -r -c PERF`

**Comment by AdityaKoranga** [comment]
Yes @hanno-becker running as root solved the issue.

Thanks once again.
